<?php

namespace Tests\Feature;

use App\Models\Department;
use App\Models\OfficePosition;
use App\Models\Training\Test;
use App\Models\Training\TestAttempt;
use App\Models\Training\TestOption;
use App\Models\Training\TestQuestion;
use App\Models\Training\Training;
use App\Models\Training\TrainingAssignment;
use App\Models\Training\TrainingCategory;
use App\Models\Training\TrainingScope;
use App\Models\Training\TrainingSession;
use App\Models\Training\TrainingSessionParticipant;
use App\Models\Training\TrainingTrigger;
use App\Models\User;
use App\Services\Training\TestEvaluationService;
use App\Services\Training\TrainingAssignmentService;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Tests\TestCase;

class TrainingMasterTest extends TestCase
{
    use DatabaseTransactions;

    public function test_user_creation_triggers_onboarding_training_assignment(): void
    {
        $code = 'ERP-SALE-' . uniqid();
        // 1. Setup Department, OfficePosition & Training with Scope
        $dept = Department::create(['name' => 'Sales Department ' . uniqid()]);
        $pos = OfficePosition::create(['name' => 'Sales Staff']);
        $cat = TrainingCategory::create(['name' => 'ERP Workflows ' . uniqid()]);

        $training = Training::create([
            'code' => $code,
            'title' => 'Odoo Sales Workflow',
            'description' => 'Standard sales workflow training',
            'training_category_id' => $cat->id,
            'retrain_interval' => 12,
            'retrain_unit' => 'month',
            'passing_score' => 80.00,
            'status' => 'active',
        ]);

        TrainingScope::create([
            'training_id' => $training->id,
            'department_id' => $dept->id,
            'office_position_id' => $pos->id,
        ]);

        // 2. Create User with matching Dept & Office Position
        $permPos = \App\Models\Position::firstOrCreate(['name' => 'General Staff']);
        $branch = \App\Models\Branch::firstOrCreate(['name' => 'HQ Branch']);
        $location = \App\Models\Location::firstOrCreate(['name' => 'HQ Location']);

        $user = User::create([
            'name' => 'John Doe',
            'email' => 'john.doe.' . uniqid() . '@example.com',
            'password' => bcrypt('password'),
            'position_id' => $permPos->id,
            'branch_id' => $branch->id,
            'location_id' => $location->id,
            'department_id' => $dept->id,
            'office_position_id' => $pos->id,
            'employment_start_date' => now()->toDateString(),
        ]);

        // 3. Assert Assignment was generated by UserTrainingObserver
        $this->assertDatabaseHas('training_assignments', [
            'training_id' => $training->id,
            'user_id' => $user->id,
            'status' => 'PENDING',
        ]);

        $this->assertDatabaseHas('training_triggers', [
            'training_id' => $training->id,
            'trigger_type' => 'NEW_USER',
            'source_id' => $user->id,
        ]);
    }

    public function test_test_evaluation_failing_and_passing_flows(): void
    {
        $code = 'FIN-CASH-' . uniqid();
        $dept = Department::create(['name' => 'Finance Dept ' . uniqid()]);
        $pos = OfficePosition::create(['name' => 'Cashier']);

        $training = Training::create([
            'code' => $code,
            'title' => 'Cash Handling SOP',
            'retrain_interval' => 6,
            'retrain_unit' => 'month',
            'passing_score' => 80.00,
            'status' => 'active',
        ]);

        $test = Test::create([
            'training_id' => $training->id,
            'title' => 'Cash SOP Test',
            'passing_score' => 80.00,
            'status' => 'active',
        ]);

        // Add 2 questions: Q1 (50 pts), Q2 (50 pts)
        $q1 = TestQuestion::create([
            'test_id' => $test->id,
            'question' => 'Always verify cash before delivery?',
            'question_type' => 'TRUE_FALSE',
            'marks' => 50,
            'sort_order' => 1,
        ]);
        $q1OptTrue = TestOption::create(['test_question_id' => $q1->id, 'answer' => 'True', 'is_correct' => true]);
        $q1OptFalse = TestOption::create(['test_question_id' => $q1->id, 'answer' => 'False', 'is_correct' => false]);

        $q2 = TestQuestion::create([
            'test_id' => $test->id,
            'question' => 'Where should currency balance be logged?',
            'question_type' => 'MULTIPLE_CHOICE',
            'marks' => 50,
            'sort_order' => 2,
        ]);
        $q2OptA = TestOption::create(['test_question_id' => $q2->id, 'answer' => 'Cash Register Book', 'is_correct' => false]);
        $q2OptB = TestOption::create(['test_question_id' => $q2->id, 'answer' => 'ERP System', 'is_correct' => true]);

        $permPos = \App\Models\Position::firstOrCreate(['name' => 'General Staff']);
        $branch = \App\Models\Branch::firstOrCreate(['name' => 'HQ Branch']);
        $location = \App\Models\Location::firstOrCreate(['name' => 'HQ Location']);

        $user = User::create([
            'name' => 'Alice Cashier',
            'email' => 'alice.' . uniqid() . '@example.com',
            'password' => bcrypt('password'),
            'position_id' => $permPos->id,
            'branch_id' => $branch->id,
            'location_id' => $location->id,
            'department_id' => $dept->id,
            'office_position_id' => $pos->id,
        ]);

        $assignment = TrainingAssignment::create([
            'training_id' => $training->id,
            'user_id' => $user->id,
            'status' => 'PENDING',
        ]);

        $session = TrainingSession::create([
            'training_id' => $training->id,
            'session_code' => 'FIN-CASH-S001',
            'title' => 'Session #1',
            'status' => 'OPEN',
        ]);

        $participant = TrainingSessionParticipant::create([
            'training_session_id' => $session->id,
            'training_assignment_id' => $assignment->id,
            'user_id' => $user->id,
            'attendance_status' => 'REGISTERED',
        ]);

        $evalService = app(TestEvaluationService::class);

        // Attempt 1: Failed (Q1 correct, Q2 wrong => 50% < 80%)
        $attempt1 = $evalService->startAttempt($test, $user, $assignment, $session->id);
        $res1 = $evalService->submitAttempt($attempt1, [
            $q1->id => $q1OptTrue->id,
            $q2->id => $q2OptA->id,
        ]);

        $this->assertEquals('FAILED', $res1['attempt']->result);
        $this->assertEquals(50.0, $res1['percentage']);
        $this->assertFalse($res1['passed']);

        // Check that Session #2 was automatically provisioned as PENDING
        $this->assertDatabaseHas('training_sessions', [
            'training_id' => $training->id,
            'status' => 'PENDING',
        ]);

        // Now mark session attendance as ATTENDED for Tier 1 requirement
        $participant->update(['attendance_status' => 'ATTENDED']);

        // Attempt 2: Passed (Q1 correct, Q2 correct => 100% >= 80%)
        $attempt2 = $evalService->startAttempt($test, $user, $assignment, $session->id);
        $res2 = $evalService->submitAttempt($attempt2, [
            $q1->id => $q1OptTrue->id,
            $q2->id => $q2OptB->id,
        ]);

        $this->assertEquals('PASSED', $res2['attempt']->result);
        $this->assertEquals(100.0, $res2['percentage']);
        $this->assertTrue($res2['passed']);
        $this->assertTrue($res2['requirement_completed']);

        // Check assignment is now marked COMPLETED with completed_at
        $assignment->refresh();
        $this->assertEquals('COMPLETED', $assignment->status);
        $this->assertNotNull($assignment->completed_at);
    }

    public function test_retraining_check_artisan_command(): void
    {
        $this->artisan('training:check-due')->assertSuccessful();
    }

    public function test_company_document_update_triggers_scoped_training_announcements(): void
    {
        config(['scout.driver' => null]);

        $dept = Department::create(['name' => 'Operations Dept ' . uniqid()]);
        $pos = OfficePosition::create(['name' => 'Branch Manager']);

        $training = Training::create([
            'code' => 'OP-WORKFLOW-' . uniqid(),
            'title' => 'Branch Operations SOP',
            'retrain_interval' => 12,
            'retrain_unit' => 'month',
            'passing_score' => 80.00,
            'status' => 'active',
        ]);

        TrainingScope::create([
            'training_id' => $training->id,
            'department_id' => $dept->id,
            'office_position_id' => $pos->id,
        ]);

        $permPos = \App\Models\Position::firstOrCreate(['name' => 'General Staff']);
        $branch = \App\Models\Branch::firstOrCreate(['name' => 'HQ Branch']);
        $location = \App\Models\Location::firstOrCreate(['name' => 'HQ Location']);

        $user = User::create([
            'name' => 'Manager Bob',
            'email' => 'bob.' . uniqid() . '@example.com',
            'password' => bcrypt('password'),
            'position_id' => $permPos->id,
            'branch_id' => $branch->id,
            'location_id' => $location->id,
            'department_id' => $dept->id,
            'office_position_id' => $pos->id,
        ]);

        $type = \App\Models\CompanyDocumentType::firstOrCreate(['name' => 'Standard SOP']);
        $doc = \App\Models\CompanyDocument::create([
            'title' => 'Branch Operations Manual',
            'body' => '<p>Initial version</p>',
            'department_id' => $dept->id,
            'company_document_type_id' => $type->id,
            'created_by' => $user->id,
            'updated_by' => $user->id,
        ]);

        // Connect document to training
        $training->companyDocuments()->attach($doc->id);
        $this->assertTrue($training->companyDocuments()->where('company_documents.id', $doc->id)->exists());
        $this->assertTrue($doc->trainings()->where('trainings.id', $training->id)->exists());

        // Update document with training_required trigger via controller
        $this->actingAs($user)->put(route('document.library.update', $doc->id), [
            'title' => 'Branch Operations Manual V2',
            'body' => '<p>Updated settlement rules</p>',
            'department_id' => $dept->id,
            'company_document_type_id' => $type->id,
            'training_required' => true,
            'training_ids' => [$training->id],
            'training_reason' => 'Settlement rules updated in V2',
        ]);

        // Assert trigger was created and user in scope was assigned
        $this->assertDatabaseHas('training_triggers', [
            'training_id' => $training->id,
            'trigger_type' => 'WORKFLOW_CHANGE',
            'reason' => 'Settlement rules updated in V2',
        ]);

        $this->assertDatabaseHas('training_assignments', [
            'training_id' => $training->id,
            'user_id' => $user->id,
            'status' => 'PENDING',
        ]);
    }

    public function test_department_wide_training_scope_affects_all_department_users_and_position_specific_scope_only_affects_position(): void
    {
        $dept = Department::create(['name' => 'HR Department ' . uniqid()]);
        $posManager = OfficePosition::create(['name' => 'HR Manager ' . uniqid()]);
        $posOfficer = OfficePosition::create(['name' => 'HR Officer ' . uniqid()]);
        $cat = TrainingCategory::create(['name' => 'General Policy ' . uniqid()]);

        // 1. Training A: Scoped to entire HR Department (office_position_id = null)
        $trainingDeptWide = Training::create([
            'code' => 'HR-ALL-' . uniqid(),
            'title' => 'HR General Conduct',
            'training_category_id' => $cat->id,
            'retrain_interval' => 12,
            'retrain_unit' => 'month',
            'passing_score' => 80.00,
            'status' => 'active',
        ]);
        TrainingScope::create([
            'training_id' => $trainingDeptWide->id,
            'department_id' => $dept->id,
            'office_position_id' => null,
        ]);

        // 2. Training B: Scoped strictly to HR Manager in HR Dept
        $trainingManagerOnly = Training::create([
            'code' => 'HR-MGR-' . uniqid(),
            'title' => 'HR Management Advanced SOP',
            'training_category_id' => $cat->id,
            'retrain_interval' => 12,
            'retrain_unit' => 'month',
            'passing_score' => 80.00,
            'status' => 'active',
        ]);
        TrainingScope::create([
            'training_id' => $trainingManagerOnly->id,
            'department_id' => $dept->id,
            'office_position_id' => $posManager->id,
        ]);

        $permPos = \App\Models\Position::firstOrCreate(['name' => 'General Staff']);
        $branch = \App\Models\Branch::firstOrCreate(['name' => 'HQ Branch']);
        $location = \App\Models\Location::firstOrCreate(['name' => 'HQ Location']);

        // User 1: HR Manager (should receive both trainings)
        $user1 = User::create([
            'name' => 'HR Manager User',
            'email' => 'hr.mgr.' . uniqid() . '@example.com',
            'password' => bcrypt('password'),
            'position_id' => $permPos->id,
            'branch_id' => $branch->id,
            'location_id' => $location->id,
            'department_id' => $dept->id,
            'office_position_id' => $posManager->id,
        ]);

        // User 2: HR Officer (should receive department-wide training only)
        $user2 = User::create([
            'name' => 'HR Officer User',
            'email' => 'hr.officer.' . uniqid() . '@example.com',
            'password' => bcrypt('password'),
            'position_id' => $permPos->id,
            'branch_id' => $branch->id,
            'location_id' => $location->id,
            'department_id' => $dept->id,
            'office_position_id' => $posOfficer->id,
        ]);

        // User 3: Employee in another department (should receive neither)
        $otherDept = Department::create(['name' => 'IT Dept ' . uniqid()]);
        $user3 = User::create([
            'name' => 'IT User',
            'email' => 'it.user.' . uniqid() . '@example.com',
            'password' => bcrypt('password'),
            'position_id' => $permPos->id,
            'branch_id' => $branch->id,
            'location_id' => $location->id,
            'department_id' => $otherDept->id,
            'office_position_id' => $posManager->id,
        ]);

        // Assert User 1 (Manager) got both trainings
        $this->assertDatabaseHas('training_assignments', [
            'training_id' => $trainingDeptWide->id,
            'user_id' => $user1->id,
        ]);
        $this->assertDatabaseHas('training_assignments', [
            'training_id' => $trainingManagerOnly->id,
            'user_id' => $user1->id,
        ]);

        // Assert User 2 (Officer) got department-wide training, but NOT the manager-only training
        $this->assertDatabaseHas('training_assignments', [
            'training_id' => $trainingDeptWide->id,
            'user_id' => $user2->id,
        ]);
        $this->assertDatabaseMissing('training_assignments', [
            'training_id' => $trainingManagerOnly->id,
            'user_id' => $user2->id,
        ]);

        // Assert User 3 (Other department) got neither
        $this->assertDatabaseMissing('training_assignments', [
            'training_id' => $trainingDeptWide->id,
            'user_id' => $user3->id,
        ]);
        $this->assertDatabaseMissing('training_assignments', [
            'training_id' => $trainingManagerOnly->id,
            'user_id' => $user3->id,
        ]);
    }

    public function test_compliance_dashboard_screen_loads_successfully(): void
    {
        $permPos = \App\Models\Position::firstOrCreate(['name' => 'General Staff']);
        $branch = \App\Models\Branch::firstOrCreate(['name' => 'HQ Branch']);
        $location = \App\Models\Location::firstOrCreate(['name' => 'HQ Location']);
        $dept = Department::firstOrCreate(['name' => 'HR Dept ' . uniqid()]);
        $pos = OfficePosition::firstOrCreate(['name' => 'Officer ' . uniqid()]);

        $user = User::create([
            'name' => 'Test Compliance Viewer',
            'email' => 'compliance.viewer.' . uniqid() . '@example.com',
            'password' => bcrypt('password'),
            'position_id' => $permPos->id,
            'branch_id' => $branch->id,
            'location_id' => $location->id,
            'department_id' => $dept->id,
            'office_position_id' => $pos->id,
        ]);

        $response = $this->actingAs($user)->get(route('training.dashboard'));
        $response->assertStatus(200);

        $user->givePermissionTo('training.catalog.view');
        $responseCatalog = $this->actingAs($user)->get(route('training.trainings.index'));
        $responseCatalog->assertStatus(200);

        $responseOfficePositions = $this->actingAs($user)->get(route('training.office-positions.index'));
        $responseOfficePositions->assertStatus(200);
    }

    public function test_custom_assignment_by_department_position_and_specific_employees(): void
    {
        $permPos = \App\Models\Position::firstOrCreate(['name' => 'General Staff']);
        $branch = \App\Models\Branch::firstOrCreate(['name' => 'HQ Branch']);
        $location = \App\Models\Location::firstOrCreate(['name' => 'HQ Location']);

        $deptA = Department::firstOrCreate(['name' => 'Dept A ' . uniqid()]);
        $deptB = Department::firstOrCreate(['name' => 'Dept B ' . uniqid()]);
        $posA = OfficePosition::firstOrCreate(['name' => 'Position A ' . uniqid()]);
        $posB = OfficePosition::firstOrCreate(['name' => 'Position B ' . uniqid()]);

        $user1 = User::create([
            'name' => 'User Dept A Pos A',
            'email' => 'u1.' . uniqid() . '@example.com',
            'password' => bcrypt('password'),
            'position_id' => $permPos->id,
            'branch_id' => $branch->id,
            'location_id' => $location->id,
            'department_id' => $deptA->id,
            'office_position_id' => $posA->id,
        ]);

        $user2 = User::create([
            'name' => 'User Dept A Pos B',
            'email' => 'u2.' . uniqid() . '@example.com',
            'password' => bcrypt('password'),
            'position_id' => $permPos->id,
            'branch_id' => $branch->id,
            'location_id' => $location->id,
            'department_id' => $deptA->id,
            'office_position_id' => $posB->id,
        ]);

        $user3 = User::create([
            'name' => 'User Dept B Pos A',
            'email' => 'u3.' . uniqid() . '@example.com',
            'password' => bcrypt('password'),
            'position_id' => $permPos->id,
            'branch_id' => $branch->id,
            'location_id' => $location->id,
            'department_id' => $deptB->id,
            'office_position_id' => $posA->id,
        ]);

        $user1->givePermissionTo('training.catalog.update');

        $training1 = Training::create([
            'code' => 'CUSTOM-DEPT-' . uniqid(),
            'title' => 'Custom Dept Assign Training',
            'retrain_interval' => 6,
            'retrain_unit' => 'month',
            'passing_score' => 80.00,
            'status' => 'active',
        ]);

        // 1. Assign by department (deptA -> user1 and user2)
        $respDept = $this->actingAs($user1)->post(route('training.trainings.assign', $training1), [
            'target_type' => 'departments',
            'department_ids' => [$deptA->id],
            'due_date' => now()->addDays(45)->toDateString(),
            'reason' => 'Department wide compliance',
        ]);
        $respDept->assertRedirect();

        $this->assertDatabaseHas('training_assignments', [
            'training_id' => $training1->id,
            'user_id' => $user1->id,
            'due_date' => now()->addDays(45)->toDateString(),
        ]);
        $this->assertDatabaseHas('training_assignments', [
            'training_id' => $training1->id,
            'user_id' => $user2->id,
        ]);
        $this->assertDatabaseMissing('training_assignments', [
            'training_id' => $training1->id,
            'user_id' => $user3->id,
        ]);

        // 2. Assign by position (posA -> user1 and user3)
        $training2 = Training::create([
            'code' => 'CUSTOM-POS-' . uniqid(),
            'title' => 'Custom Position Assign Training',
            'retrain_interval' => 12,
            'retrain_unit' => 'month',
            'passing_score' => 80.00,
            'status' => 'active',
        ]);

        $respPos = $this->actingAs($user1)->post(route('training.trainings.assign', $training2), [
            'target_type' => 'positions',
            'office_position_ids' => [$posA->id],
        ]);
        $respPos->assertRedirect();

        $this->assertDatabaseHas('training_assignments', [
            'training_id' => $training2->id,
            'user_id' => $user1->id,
        ]);
        $this->assertDatabaseHas('training_assignments', [
            'training_id' => $training2->id,
            'user_id' => $user3->id,
        ]);
        $this->assertDatabaseMissing('training_assignments', [
            'training_id' => $training2->id,
            'user_id' => $user2->id,
        ]);

        // 3. Assign to specific multi-select employees (only user2 and user3)
        $training3 = Training::create([
            'code' => 'CUSTOM-EMP-' . uniqid(),
            'title' => 'Custom Specific Employees Training',
            'retrain_interval' => 12,
            'retrain_unit' => 'month',
            'passing_score' => 80.00,
            'status' => 'active',
        ]);

        $respEmp = $this->actingAs($user1)->post(route('training.trainings.assign', $training3), [
            'target_type' => 'employees',
            'user_ids' => [$user2->id, $user3->id],
            'due_date' => now()->addDays(14)->toDateString(),
            'reason' => 'Direct assignment to specific staff',
        ]);
        $respEmp->assertRedirect();

        $this->assertDatabaseMissing('training_assignments', [
            'training_id' => $training3->id,
            'user_id' => $user1->id,
        ]);
        $this->assertDatabaseHas('training_assignments', [
            'training_id' => $training3->id,
            'user_id' => $user2->id,
            'due_date' => now()->addDays(14)->toDateString(),
        ]);
        $this->assertDatabaseHas('training_assignments', [
            'training_id' => $training3->id,
            'user_id' => $user3->id,
            'due_date' => now()->addDays(14)->toDateString(),
        ]);
    }

    public function test_trigger_question_test_only_without_training_session(): void
    {
        $permPos = \App\Models\Position::firstOrCreate(['name' => 'General Staff']);
        $branch = \App\Models\Branch::firstOrCreate(['name' => 'HQ Branch']);
        $location = \App\Models\Location::firstOrCreate(['name' => 'HQ Location']);
        $dept = Department::firstOrCreate(['name' => 'IT Department ' . uniqid()]);
        $pos = OfficePosition::firstOrCreate(['name' => 'Developer ' . uniqid()]);

        $user = User::create([
            'name' => 'Test Retest User',
            'email' => 'retest.' . uniqid() . '@example.com',
            'password' => bcrypt('password'),
            'position_id' => $permPos->id,
            'branch_id' => $branch->id,
            'location_id' => $location->id,
            'department_id' => $dept->id,
            'office_position_id' => $pos->id,
        ]);

        $training = Training::create([
            'code' => 'TEST-ONLY-' . uniqid(),
            'title' => 'Standalone Security Quiz',
            'retrain_interval' => 12,
            'retrain_unit' => 'month',
            'passing_score' => 70.00,
            'status' => 'active',
        ]);

        // Create a test attached to training
        $test = \App\Models\Training\Test::create([
            'training_id' => $training->id,
            'title' => 'Security Knowledge Check',
            'passing_score' => 70.00,
            'time_limit_minutes' => 15,
            'status' => 'active',
        ]);

        $q1 = \App\Models\Training\TestQuestion::create([
            'test_id' => $test->id,
            'question' => 'What is 2FA?',
            'marks' => 10,
            'sort_order' => 1,
        ]);

        $optCorrect = \App\Models\Training\TestOption::create([
            'test_question_id' => $q1->id,
            'answer' => 'Two-Factor Authentication',
            'is_correct' => true,
            'sort_order' => 1,
        ]);

        $optWrong = \App\Models\Training\TestOption::create([
            'test_question_id' => $q1->id,
            'answer' => 'Two Fast Animals',
            'is_correct' => false,
            'sort_order' => 2,
        ]);

        $user->givePermissionTo('training.catalog.update');

        // 1. Trigger TEST_ONLY assignment
        $resp = $this->actingAs($user)->post(route('training.trainings.assign', $training), [
            'target_type' => 'employees',
            'assignment_type' => 'TEST_ONLY',
            'user_ids' => [$user->id],
            'reason' => 'Annual re-exam knowledge check',
        ]);
        $resp->assertRedirect();

        $assignment = \App\Models\Training\TrainingAssignment::where('training_id', $training->id)
            ->where('user_id', $user->id)
            ->firstOrFail();

        $this->assertEquals('TEST_ONLY', $assignment->assignment_type);
        $this->assertEquals('PENDING', $assignment->status);

        // Verify NO training sessions were provisioned
        $this->assertDatabaseMissing('training_session_participants', [
            'training_assignment_id' => $assignment->id,
        ]);

        // 2. Submit passing test answers -> Should complete immediately without session attendance
        $evaluationService = app(\App\Services\Training\TestEvaluationService::class);
        $attempt = $evaluationService->startAttempt($test, $user, $assignment);
        $result = $evaluationService->submitAttempt($attempt, [
            $q1->id => $optCorrect->id,
        ]);

        $this->assertTrue($result['passed']);
        $this->assertTrue($result['requirement_completed']);
        $this->assertEquals('COMPLETED', $assignment->fresh()->status);
        $this->assertNotNull($assignment->fresh()->completed_at);
    }

    public function test_training_catalog_route_permissions_enforcement(): void
    {
        $permPos = \App\Models\Position::firstOrCreate(['name' => 'General Staff']);
        $branch = \App\Models\Branch::firstOrCreate(['name' => 'HQ Branch']);
        $location = \App\Models\Location::firstOrCreate(['name' => 'HQ Location']);
        $dept = Department::firstOrCreate(['name' => 'HR Dept ' . uniqid()]);
        $pos = OfficePosition::firstOrCreate(['name' => 'HR Specialist ' . uniqid()]);

        $unauthorizedUser = User::create([
            'name' => 'Unauthorized Staff',
            'email' => 'unauth.' . uniqid() . '@example.com',
            'password' => bcrypt('password'),
            'position_id' => $permPos->id,
            'branch_id' => $branch->id,
            'location_id' => $location->id,
            'department_id' => $dept->id,
            'office_position_id' => $pos->id,
        ]);

        $authorizedUser = User::create([
            'name' => 'Catalog Manager',
            'email' => 'manager.' . uniqid() . '@example.com',
            'password' => bcrypt('password'),
            'position_id' => $permPos->id,
            'branch_id' => $branch->id,
            'location_id' => $location->id,
            'department_id' => $dept->id,
            'office_position_id' => $pos->id,
        ]);

        $training = Training::create([
            'code' => 'PERM-TEST-' . uniqid(),
            'title' => 'Permission Protected Course',
            'retrain_interval' => 12,
            'retrain_unit' => 'month',
            'passing_score' => 80.00,
            'status' => 'active',
        ]);

        // 1. Unauthorized user cannot access catalog index (403)
        $this->actingAs($unauthorizedUser)->get(route('training.trainings.index'))->assertStatus(403);

        // 2. Unauthorized user cannot create training (403)
        $this->actingAs($unauthorizedUser)->post(route('training.trainings.store'), [
            'code' => 'FORBIDDEN-01',
            'title' => 'Forbidden Course',
            'retrain_interval' => 12,
            'retrain_unit' => 'month',
            'passing_score' => 80,
            'status' => 'active',
        ])->assertStatus(403);

        // 3. Unauthorized user cannot update or delete (403)
        $this->actingAs($unauthorizedUser)->put(route('training.trainings.update', $training), [
            'code' => $training->code,
            'title' => 'Hacked Title',
            'retrain_interval' => 12,
            'retrain_unit' => 'month',
            'passing_score' => 80,
            'status' => 'active',
        ])->assertStatus(403);

        $this->actingAs($unauthorizedUser)->delete(route('training.trainings.destroy', $training))->assertStatus(403);

        // 4. Grant individual permissions to authorizedUser and verify success
        $authorizedUser->givePermissionTo('training.catalog.view');
        $this->actingAs($authorizedUser)->get(route('training.trainings.index'))->assertStatus(200);

        $authorizedUser->givePermissionTo('training.catalog.create');
        $newCode = 'PERM-CREATED-' . uniqid();
        $this->actingAs($authorizedUser)->post(route('training.trainings.store'), [
            'code' => $newCode,
            'title' => 'Authorized New Course',
            'retrain_interval' => 12,
            'retrain_unit' => 'month',
            'passing_score' => 80,
            'status' => 'active',
        ])->assertRedirect();
        $this->assertDatabaseHas('trainings', ['code' => $newCode]);

        $createdTraining = Training::where('code', $newCode)->firstOrFail();

        $authorizedUser->givePermissionTo('training.catalog.update');
        $this->actingAs($authorizedUser)->put(route('training.trainings.update', $createdTraining), [
            'code' => $newCode,
            'title' => 'Updated Authorized Course',
            'retrain_interval' => 6,
            'retrain_unit' => 'month',
            'passing_score' => 85,
            'status' => 'active',
        ])->assertRedirect();
        $this->assertEquals('Updated Authorized Course', $createdTraining->fresh()->title);

        $authorizedUser->givePermissionTo('training.catalog.delete');
        $this->actingAs($authorizedUser)->delete(route('training.trainings.destroy', $createdTraining))->assertRedirect();
        $this->assertDatabaseMissing('trainings', ['id' => $createdTraining->id]);
    }
}
