<?php

namespace Tests\Feature;

use App\Models\Department;
use App\Models\OfficePosition;
use App\Models\Training\Test;
use App\Models\Training\TestAttempt;
use App\Models\Training\TestOption;
use App\Models\Training\TestQuestion;
use App\Models\Training\Training;
use App\Models\Training\TrainingAssignment;
use App\Models\Training\TrainingCategory;
use App\Models\Training\TrainingScope;
use App\Models\Training\TrainingSession;
use App\Models\Training\TrainingSessionParticipant;
use App\Models\Training\TrainingTrigger;
use App\Models\User;
use App\Services\Training\TestEvaluationService;
use App\Services\Training\TrainingAssignmentService;
use Illuminate\Foundation\Testing\DatabaseTransactions;
use Tests\TestCase;

class TrainingMasterTest extends TestCase
{
    use DatabaseTransactions;

    public function test_user_creation_triggers_onboarding_training_assignment(): void
    {
        $code = 'ERP-SALE-' . uniqid();
        // 1. Setup Department, OfficePosition & Training with Scope
        $dept = Department::create(['name' => 'Sales Department ' . uniqid()]);
        $pos = OfficePosition::create(['name' => 'Sales Staff']);
        $cat = TrainingCategory::create(['name' => 'ERP Workflows ' . uniqid()]);

        $training = Training::create([
            'code' => $code,
            'title' => 'Odoo Sales Workflow',
            'description' => 'Standard sales workflow training',
            'training_category_id' => $cat->id,
            'retrain_interval' => 12,
            'retrain_unit' => 'month',
            'passing_score' => 80.00,
            'status' => 'active',
        ]);

        TrainingScope::create([
            'training_id' => $training->id,
            'department_id' => $dept->id,
            'office_position_id' => $pos->id,
        ]);

        // 2. Create User with matching Dept & Office Position
        $permPos = \App\Models\Position::firstOrCreate(['name' => 'General Staff']);
        $branch = \App\Models\Branch::firstOrCreate(['name' => 'HQ Branch']);
        $location = \App\Models\Location::firstOrCreate(['name' => 'HQ Location']);

        $user = User::create([
            'name' => 'John Doe',
            'email' => 'john.doe.' . uniqid() . '@example.com',
            'password' => bcrypt('password'),
            'position_id' => $permPos->id,
            'branch_id' => $branch->id,
            'location_id' => $location->id,
            'department_id' => $dept->id,
            'office_position_id' => $pos->id,
            'employment_start_date' => now()->toDateString(),
        ]);

        // 3. Assert Assignment was generated by UserTrainingObserver
        $this->assertDatabaseHas('training_assignments', [
            'training_id' => $training->id,
            'user_id' => $user->id,
            'status' => 'PENDING',
        ]);

        $this->assertDatabaseHas('training_triggers', [
            'training_id' => $training->id,
            'trigger_type' => 'NEW_USER',
            'source_id' => $user->id,
        ]);
    }

    public function test_test_evaluation_failing_and_passing_flows(): void
    {
        $code = 'FIN-CASH-' . uniqid();
        $dept = Department::create(['name' => 'Finance Dept ' . uniqid()]);
        $pos = OfficePosition::create(['name' => 'Cashier']);

        $training = Training::create([
            'code' => $code,
            'title' => 'Cash Handling SOP',
            'retrain_interval' => 6,
            'retrain_unit' => 'month',
            'passing_score' => 80.00,
            'status' => 'active',
        ]);

        $test = Test::create([
            'training_id' => $training->id,
            'title' => 'Cash SOP Test',
            'passing_score' => 80.00,
            'status' => 'active',
        ]);

        // Add 2 questions: Q1 (50 pts), Q2 (50 pts)
        $q1 = TestQuestion::create([
            'test_id' => $test->id,
            'question' => 'Always verify cash before delivery?',
            'question_type' => 'TRUE_FALSE',
            'marks' => 50,
            'sort_order' => 1,
        ]);
        $q1OptTrue = TestOption::create(['test_question_id' => $q1->id, 'answer' => 'True', 'is_correct' => true]);
        $q1OptFalse = TestOption::create(['test_question_id' => $q1->id, 'answer' => 'False', 'is_correct' => false]);

        $q2 = TestQuestion::create([
            'test_id' => $test->id,
            'question' => 'Where should currency balance be logged?',
            'question_type' => 'MULTIPLE_CHOICE',
            'marks' => 50,
            'sort_order' => 2,
        ]);
        $q2OptA = TestOption::create(['test_question_id' => $q2->id, 'answer' => 'Cash Register Book', 'is_correct' => false]);
        $q2OptB = TestOption::create(['test_question_id' => $q2->id, 'answer' => 'ERP System', 'is_correct' => true]);

        $permPos = \App\Models\Position::firstOrCreate(['name' => 'General Staff']);
        $branch = \App\Models\Branch::firstOrCreate(['name' => 'HQ Branch']);
        $location = \App\Models\Location::firstOrCreate(['name' => 'HQ Location']);

        $user = User::create([
            'name' => 'Alice Cashier',
            'email' => 'alice.' . uniqid() . '@example.com',
            'password' => bcrypt('password'),
            'position_id' => $permPos->id,
            'branch_id' => $branch->id,
            'location_id' => $location->id,
            'department_id' => $dept->id,
            'office_position_id' => $pos->id,
        ]);

        $assignment = TrainingAssignment::create([
            'training_id' => $training->id,
            'user_id' => $user->id,
            'status' => 'PENDING',
        ]);

        $session = TrainingSession::create([
            'training_id' => $training->id,
            'session_code' => 'FIN-CASH-S001',
            'title' => 'Session #1',
            'status' => 'OPEN',
        ]);

        $participant = TrainingSessionParticipant::create([
            'training_session_id' => $session->id,
            'training_assignment_id' => $assignment->id,
            'user_id' => $user->id,
            'attendance_status' => 'REGISTERED',
        ]);

        $evalService = app(TestEvaluationService::class);

        // Attempt 1: Failed (Q1 correct, Q2 wrong => 50% < 80%)
        $attempt1 = $evalService->startAttempt($test, $user, $assignment, $session->id);
        $res1 = $evalService->submitAttempt($attempt1, [
            $q1->id => $q1OptTrue->id,
            $q2->id => $q2OptA->id,
        ]);

        $this->assertEquals('FAILED', $res1['attempt']->result);
        $this->assertEquals(50.0, $res1['percentage']);
        $this->assertFalse($res1['passed']);

        // Check that Session #2 was automatically provisioned as PENDING
        $this->assertDatabaseHas('training_sessions', [
            'training_id' => $training->id,
            'status' => 'PENDING',
        ]);

        // Now mark session attendance as ATTENDED for Tier 1 requirement
        $participant->update(['attendance_status' => 'ATTENDED']);

        // Attempt 2: Passed (Q1 correct, Q2 correct => 100% >= 80%)
        $attempt2 = $evalService->startAttempt($test, $user, $assignment, $session->id);
        $res2 = $evalService->submitAttempt($attempt2, [
            $q1->id => $q1OptTrue->id,
            $q2->id => $q2OptB->id,
        ]);

        $this->assertEquals('PASSED', $res2['attempt']->result);
        $this->assertEquals(100.0, $res2['percentage']);
        $this->assertTrue($res2['passed']);
        $this->assertTrue($res2['requirement_completed']);

        // Check assignment is now marked COMPLETED with completed_at
        $assignment->refresh();
        $this->assertEquals('COMPLETED', $assignment->status);
        $this->assertNotNull($assignment->completed_at);
    }

    public function test_retraining_check_artisan_command(): void
    {
        $this->artisan('training:check-due')->assertSuccessful();
    }

    public function test_company_document_update_triggers_scoped_training_announcements(): void
    {
        config(['scout.driver' => null]);

        $dept = Department::create(['name' => 'Operations Dept ' . uniqid()]);
        $pos = OfficePosition::create(['name' => 'Branch Manager']);

        $training = Training::create([
            'code' => 'OP-WORKFLOW-' . uniqid(),
            'title' => 'Branch Operations SOP',
            'retrain_interval' => 12,
            'retrain_unit' => 'month',
            'passing_score' => 80.00,
            'status' => 'active',
        ]);

        TrainingScope::create([
            'training_id' => $training->id,
            'department_id' => $dept->id,
            'office_position_id' => $pos->id,
        ]);

        $permPos = \App\Models\Position::firstOrCreate(['name' => 'General Staff']);
        $branch = \App\Models\Branch::firstOrCreate(['name' => 'HQ Branch']);
        $location = \App\Models\Location::firstOrCreate(['name' => 'HQ Location']);

        $user = User::create([
            'name' => 'Manager Bob',
            'email' => 'bob.' . uniqid() . '@example.com',
            'password' => bcrypt('password'),
            'position_id' => $permPos->id,
            'branch_id' => $branch->id,
            'location_id' => $location->id,
            'department_id' => $dept->id,
            'office_position_id' => $pos->id,
        ]);

        $type = \App\Models\CompanyDocumentType::firstOrCreate(['name' => 'Standard SOP']);
        $doc = \App\Models\CompanyDocument::create([
            'title' => 'Branch Operations Manual',
            'body' => '<p>Initial version</p>',
            'department_id' => $dept->id,
            'company_document_type_id' => $type->id,
            'created_by' => $user->id,
            'updated_by' => $user->id,
        ]);

        // Connect document to training
        $training->companyDocuments()->attach($doc->id);
        $this->assertTrue($training->companyDocuments()->where('company_documents.id', $doc->id)->exists());
        $this->assertTrue($doc->trainings()->where('trainings.id', $training->id)->exists());

        // Update document with training_required trigger via controller
        $this->actingAs($user)->put(route('document.library.update', $doc->id), [
            'title' => 'Branch Operations Manual V2',
            'body' => '<p>Updated settlement rules</p>',
            'department_id' => $dept->id,
            'company_document_type_id' => $type->id,
            'training_required' => true,
            'training_ids' => [$training->id],
            'training_reason' => 'Settlement rules updated in V2',
        ]);

        // Assert trigger was created and user in scope was assigned
        $this->assertDatabaseHas('training_triggers', [
            'training_id' => $training->id,
            'trigger_type' => 'WORKFLOW_CHANGE',
            'reason' => 'Settlement rules updated in V2',
        ]);

        $this->assertDatabaseHas('training_assignments', [
            'training_id' => $training->id,
            'user_id' => $user->id,
            'status' => 'PENDING',
        ]);
    }

    public function test_department_wide_training_scope_affects_all_department_users_and_position_specific_scope_only_affects_position(): void
    {
        $dept = Department::create(['name' => 'HR Department ' . uniqid()]);
        $posManager = OfficePosition::create(['name' => 'HR Manager ' . uniqid()]);
        $posOfficer = OfficePosition::create(['name' => 'HR Officer ' . uniqid()]);
        $cat = TrainingCategory::create(['name' => 'General Policy ' . uniqid()]);

        // 1. Training A: Scoped to entire HR Department (office_position_id = null)
        $trainingDeptWide = Training::create([
            'code' => 'HR-ALL-' . uniqid(),
            'title' => 'HR General Conduct',
            'training_category_id' => $cat->id,
            'retrain_interval' => 12,
            'retrain_unit' => 'month',
            'passing_score' => 80.00,
            'status' => 'active',
        ]);
        TrainingScope::create([
            'training_id' => $trainingDeptWide->id,
            'department_id' => $dept->id,
            'office_position_id' => null,
        ]);

        // 2. Training B: Scoped strictly to HR Manager in HR Dept
        $trainingManagerOnly = Training::create([
            'code' => 'HR-MGR-' . uniqid(),
            'title' => 'HR Management Advanced SOP',
            'training_category_id' => $cat->id,
            'retrain_interval' => 12,
            'retrain_unit' => 'month',
            'passing_score' => 80.00,
            'status' => 'active',
        ]);
        TrainingScope::create([
            'training_id' => $trainingManagerOnly->id,
            'department_id' => $dept->id,
            'office_position_id' => $posManager->id,
        ]);

        $permPos = \App\Models\Position::firstOrCreate(['name' => 'General Staff']);
        $branch = \App\Models\Branch::firstOrCreate(['name' => 'HQ Branch']);
        $location = \App\Models\Location::firstOrCreate(['name' => 'HQ Location']);

        // User 1: HR Manager (should receive both trainings)
        $user1 = User::create([
            'name' => 'HR Manager User',
            'email' => 'hr.mgr.' . uniqid() . '@example.com',
            'password' => bcrypt('password'),
            'position_id' => $permPos->id,
            'branch_id' => $branch->id,
            'location_id' => $location->id,
            'department_id' => $dept->id,
            'office_position_id' => $posManager->id,
        ]);

        // User 2: HR Officer (should receive department-wide training only)
        $user2 = User::create([
            'name' => 'HR Officer User',
            'email' => 'hr.officer.' . uniqid() . '@example.com',
            'password' => bcrypt('password'),
            'position_id' => $permPos->id,
            'branch_id' => $branch->id,
            'location_id' => $location->id,
            'department_id' => $dept->id,
            'office_position_id' => $posOfficer->id,
        ]);

        // User 3: Employee in another department (should receive neither)
        $otherDept = Department::create(['name' => 'IT Dept ' . uniqid()]);
        $user3 = User::create([
            'name' => 'IT User',
            'email' => 'it.user.' . uniqid() . '@example.com',
            'password' => bcrypt('password'),
            'position_id' => $permPos->id,
            'branch_id' => $branch->id,
            'location_id' => $location->id,
            'department_id' => $otherDept->id,
            'office_position_id' => $posManager->id,
        ]);

        // Assert User 1 (Manager) got both trainings
        $this->assertDatabaseHas('training_assignments', [
            'training_id' => $trainingDeptWide->id,
            'user_id' => $user1->id,
        ]);
        $this->assertDatabaseHas('training_assignments', [
            'training_id' => $trainingManagerOnly->id,
            'user_id' => $user1->id,
        ]);

        // Assert User 2 (Officer) got department-wide training, but NOT the manager-only training
        $this->assertDatabaseHas('training_assignments', [
            'training_id' => $trainingDeptWide->id,
            'user_id' => $user2->id,
        ]);
        $this->assertDatabaseMissing('training_assignments', [
            'training_id' => $trainingManagerOnly->id,
            'user_id' => $user2->id,
        ]);

        // Assert User 3 (Other department) got neither
        $this->assertDatabaseMissing('training_assignments', [
            'training_id' => $trainingDeptWide->id,
            'user_id' => $user3->id,
        ]);
        $this->assertDatabaseMissing('training_assignments', [
            'training_id' => $trainingManagerOnly->id,
            'user_id' => $user3->id,
        ]);
    }

    public function test_compliance_dashboard_screen_loads_successfully(): void
    {
        $permPos = \App\Models\Position::firstOrCreate(['name' => 'General Staff']);
        $branch = \App\Models\Branch::firstOrCreate(['name' => 'HQ Branch']);
        $location = \App\Models\Location::firstOrCreate(['name' => 'HQ Location']);
        $dept = Department::firstOrCreate(['name' => 'HR Dept ' . uniqid()]);
        $pos = OfficePosition::firstOrCreate(['name' => 'Officer ' . uniqid()]);

        $user = User::create([
            'name' => 'Test Compliance Viewer',
            'email' => 'compliance.viewer.' . uniqid() . '@example.com',
            'password' => bcrypt('password'),
            'position_id' => $permPos->id,
            'branch_id' => $branch->id,
            'location_id' => $location->id,
            'department_id' => $dept->id,
            'office_position_id' => $pos->id,
        ]);

        $response = $this->actingAs($user)->get(route('training.dashboard'));
        $response->assertStatus(200);

        $responseCatalog = $this->actingAs($user)->get(route('training.trainings.index'));
        $responseCatalog->assertStatus(200);

        $responseOfficePositions = $this->actingAs($user)->get(route('training.office-positions.index'));
        $responseOfficePositions->assertStatus(200);
    }
}
